version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: